from __future__ import annotations

from PySide6.QtCore import QTimer, Qt
from PySide6.QtGui import QKeySequence, QShortcut
from PySide6.QtWidgets import (
    QAbstractItemView,
    QCheckBox,
    QFormLayout,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QProgressBar,
    QPushButton,
    QRadioButton,
    QSizePolicy,
    QSplitter,
    QStackedWidget,
    QTableWidget,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from .tif_gpu_volume_canvas import GPU_VOLUME_MAX_RAY_STEPS, GPU_VOLUME_MAX_TEXTURE_DIM
from .tif_workbench_canvas import MirroredStatusLabel, TifSliceCanvas, TifSpecimenTree, TifVolumeCanvas, WheelSafeComboBox, WheelSafeSlider
from .tif_workbench_control_panels import build_right_control_panel
from .tif_workbench_pages import build_task_pages
from .tif_workbench_translations import tt


class TifWorkbenchViewBuilder:
    def __init__(self, workbench):
        self.workbench = workbench

    def create_widgets(self):
        self = self.workbench
        self.specimen_list = TifSpecimenTree()
        self.specimen_list.setObjectName("tifSpecimenList")
        self.specimen_list.setHeaderHidden(True)
        self.specimen_list.setContextMenuPolicy(Qt.CustomContextMenu)

        self.canvas = TifSliceCanvas()
        self.canvas.workbench = self
        self.canvas.set_theme(self.current_theme)
        self.volume_canvas = TifVolumeCanvas()
        self.volume_canvas.workbench = self
        self.volume_canvas.set_theme(self.current_theme)
        self.volume_canvas.setProperty("tifVolumeRenderer", "placeholder")
        self._volume_canvas_created = False
        if hasattr(self, "volume_render_status_label"):
            self.volume_render_status_label.setVisible(False)
        self._reset_canvas_view_on_next_render = False
        self.display_mode_combo = WheelSafeComboBox()
        self.display_mode_combo.setObjectName("tifDisplayModeCombo")
        self._populate_display_mode_combo()
        self.display_mode_combo.currentIndexChanged.connect(self.on_display_mode_changed)
        self.slice_slider = WheelSafeSlider(Qt.Horizontal)
        self.slice_slider.setRange(0, 0)
        self.slice_slider.valueChanged.connect(self.on_slice_slider_changed)
        self.slice_prefix_label = QLabel("Slice")
        self.slice_label = QLabel("0 / 0")
        self.slice_axis_combo = WheelSafeComboBox()
        self.slice_axis_combo.setObjectName("tifSliceAxisCombo")
        self._populate_slice_axis_combo()
        self.slice_axis_combo.currentIndexChanged.connect(self.on_slice_axis_changed)

        self.label_role_combo = WheelSafeComboBox()
        self._populate_label_role_combo()
        self.label_role_combo.currentIndexChanged.connect(self._reload_label_volume)
        self.label_role_help_label = QLabel("")
        self.label_role_help_label.setObjectName("tifLayerHelpText")
        self.label_role_help_label.setWordWrap(True)
        self.ai_review_check_title_label = QLabel("AI review check")
        self.ai_review_check_title_label.setObjectName("tifAiReviewCheckTitle")
        self.ai_review_check_label = QLabel("")
        self.ai_review_check_label.setObjectName("tifAiReviewCheckText")
        self.ai_review_check_label.setWordWrap(True)
        self.ai_review_check_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)

        self.opacity_slider = WheelSafeSlider(Qt.Horizontal)
        self.opacity_slider.setRange(0, 100)
        self.opacity_slider.setValue(45)
        self.opacity_slider.valueChanged.connect(self.render_current_slice)
        self.brightness_slider = WheelSafeSlider(Qt.Horizontal)
        self.brightness_slider.setRange(-100, 100)
        self.brightness_slider.setValue(0)
        self.brightness_slider.valueChanged.connect(self.render_current_slice)
        self.contrast_slider = WheelSafeSlider(Qt.Horizontal)
        self.contrast_slider.setRange(1, 30)
        self.contrast_slider.setValue(10)
        self.contrast_slider.valueChanged.connect(self.render_current_slice)
        self.volume_cutoff_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_cutoff_slider.setObjectName("tifVolumeCutoffSlider")
        self.volume_cutoff_slider.setRange(0, 95)
        self.volume_cutoff_slider.setValue(35)
        self.volume_projection_combo = WheelSafeComboBox()
        self.volume_projection_combo.setObjectName("tifVolumeProjectionCombo")
        self.volume_quality_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_quality_slider.setObjectName("tifVolumeQualitySlider")
        self.volume_quality_slider.setRange(128, GPU_VOLUME_MAX_TEXTURE_DIM)
        self.volume_quality_slider.setValue(1024)
        self.volume_quality_slider.setTracking(False)
        self._volume_quality_committed_value = int(self.volume_quality_slider.value())
        self._volume_quality_drag_pending = False
        self.volume_sample_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_sample_slider.setObjectName("tifVolumeSampleSlider")
        self.volume_sample_slider.setRange(256, GPU_VOLUME_MAX_RAY_STEPS)
        self.volume_sample_slider.setValue(1536)
        self.volume_clarity_check = QCheckBox("Clarity mode")
        self.volume_clarity_check.setObjectName("tifVolumeClarityCheck")
        self.volume_roi_detail_check = QCheckBox("ROI high detail")
        self.volume_roi_detail_check.setObjectName("tifVolumeRoiDetailCheck")
        self.volume_roi_detail_check.setChecked(True)
        self.volume_roi_source_combo = WheelSafeComboBox()
        self.volume_roi_source_combo.setObjectName("tifVolumeRoiSourceCombo")
        self._populate_volume_roi_source_combo()
        self.volume_roi_inspect_check = QCheckBox("Inspect ROI crop")
        self.volume_roi_inspect_check.setObjectName("tifVolumeRoiInspectCheck")
        self.volume_roi_inspect_check.setChecked(False)
        self.volume_roi_scale_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_roi_scale_slider.setObjectName("tifVolumeRoiScaleSlider")
        self.volume_roi_scale_slider.setRange(100, 300)
        self.volume_roi_scale_slider.setValue(200)
        self.volume_roi_scale_slider.setTracking(False)
        self._volume_roi_scale_committed_value = int(self.volume_roi_scale_slider.value())
        self.volume_roi_budget_combo = WheelSafeComboBox()
        self.volume_roi_budget_combo.setObjectName("tifVolumeRoiBudgetCombo")
        self.volume_roi_budget_combo.addItem("Balanced 1.5 GB", "balanced")
        self.volume_roi_budget_combo.addItem("High 2.5 GB", "high")
        self.volume_inside_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_inside_slider.setObjectName("tifVolumeInsideSlider")
        self.volume_inside_slider.setRange(0, 160)
        self.volume_inside_slider.setValue(0)
        self.volume_clip_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_clip_slider.setObjectName("tifVolumeClipSlider")
        self.volume_clip_slider.setRange(0, 92)
        self.volume_clip_slider.setValue(0)
        self.volume_tint_combo = WheelSafeComboBox()
        self.volume_tint_combo.setObjectName("tifVolumeTintCombo")
        self._populate_volume_tint_combo()
        self.btn_volume_custom_color = QPushButton("Choose color")
        self.btn_volume_custom_color.setObjectName("tifVolumeCustomColorButton")
        self.btn_volume_morphology_preset = QPushButton("Morphology Inspect")
        self.btn_volume_morphology_preset.setObjectName("tifVolumeMorphologyPresetButton")
        self.volume_transfer_opacity_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_transfer_opacity_slider.setObjectName("tifVolumeTransferOpacitySlider")
        self.volume_transfer_opacity_slider.setRange(25, 140)
        self.volume_transfer_opacity_slider.setValue(100)
        self._volume_transfer_opacity_drag_pending = False
        self.volume_enhancement_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_enhancement_slider.setObjectName("tifVolumeEnhancementSlider")
        self.volume_enhancement_slider.setRange(0, 100)
        self.volume_enhancement_slider.setValue(35)
        self.volume_tone_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_tone_slider.setObjectName("tifVolumeToneSlider")
        self.volume_tone_slider.setRange(70, 130)
        self.volume_tone_slider.setValue(100)
        self.volume_shader_quality_combo = WheelSafeComboBox()
        self.volume_shader_quality_combo.setObjectName("tifVolumeShaderQualityCombo")
        self._populate_volume_shader_quality_combo()
        self.volume_surface_refine_check = QCheckBox("Surface refine")
        self.volume_surface_refine_check.setObjectName("tifVolumeSurfaceRefineCheck")
        self.volume_surface_refine_check.setChecked(True)
        self.volume_clip_plane_check = QCheckBox("Clip plane")
        self.volume_clip_plane_check.setObjectName("tifVolumeClipPlaneCheck")
        self.volume_clip_plane_check.setChecked(False)
        self.volume_local_axes_check = QCheckBox("Show local axes")
        self.volume_local_axes_check.setObjectName("tifVolumeLocalAxesCheck")
        self.volume_local_axes_check.setChecked(False)
        self.volume_local_axes_check.toggled.connect(self.local_axis_controller.update_summary)
        self.volume_clip_plane_depth_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_clip_plane_depth_slider.setObjectName("tifVolumeClipPlaneDepthSlider")
        self.volume_clip_plane_depth_slider.setRange(0, 100)
        self.volume_clip_plane_depth_slider.setValue(0)
        self.volume_clip_plane_depth_label = QLabel("Clip depth")
        self.volume_mask_combo = WheelSafeComboBox()
        self.volume_mask_combo.setObjectName("tifVolumeMaskCombo")
        self._populate_volume_mask_combo()
        self.volume_mask_opacity_slider = WheelSafeSlider(Qt.Horizontal)
        self.volume_mask_opacity_slider.setObjectName("tifVolumeMaskOpacitySlider")
        self.volume_mask_opacity_slider.setRange(0, 100)
        self.volume_mask_opacity_slider.setValue(45)
        self.btn_reset_volume_view = QPushButton("Reset 3D view")
        self.btn_reset_volume_view.setObjectName("tifResetVolumeViewButton")
        self.volume_render_status_label = QLabel("")
        self.volume_render_status_label.setObjectName("tifVolumeRenderStatus")
        self.volume_render_status_label.setWordWrap(False)
        status_height = max(26, self.volume_render_status_label.fontMetrics().height() + 12)
        self.volume_render_status_label.setMinimumHeight(status_height)
        self.volume_render_status_label.setMaximumHeight(status_height)
        self.volume_render_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Fixed)
        self.volume_render_status_label.setVisible(False)
        self.local_axis_summary_label = QLabel("")
        self.local_axis_summary_label.setObjectName("tifLocalAxisSummaryText")
        self.local_axis_summary_label.setWordWrap(True)
        self.local_axis_summary_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.local_axis_details_check = QCheckBox("Show axis details")
        self.local_axis_details_check.setObjectName("tifLocalAxisDetailsCheck")
        self.local_axis_details_check.setChecked(False)
        self.local_axis_details_check.toggled.connect(self.local_axis_controller.update_summary)
        self.local_axis_details_label = QLabel("")
        self.local_axis_details_label.setObjectName("tifLocalAxisDetailsText")
        self.local_axis_details_label.setWordWrap(True)
        self.local_axis_details_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.local_axis_status_label = QLabel("")
        self.local_axis_status_label.setObjectName("tifLocalAxisStatusText")
        self.local_axis_status_label.setWordWrap(True)
        self.local_axis_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)

        self.status_label = QLabel("")
        self.status_label.setObjectName("tifStatusText")
        self.status_label.setWordWrap(True)
        self.status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.metadata_label = QLabel("")
        self.metadata_label.setObjectName("tifMetadataText")
        self.metadata_label.setWordWrap(True)
        self.metadata_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.metadata_label.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.show_debug_paths_check = QCheckBox("Show debug paths")
        self.show_debug_paths_check.setObjectName("tifShowDebugPathsCheck")
        self.show_debug_paths_check.setChecked(False)
        self.show_debug_paths_check.toggled.connect(self._on_show_debug_paths_toggled)
        self.material_table = QTableWidget(0, 4)
        self.material_table.setObjectName("tifMaterialTable")
        self.material_table.setMinimumHeight(150)
        self.material_table.setMaximumHeight(240)
        self.material_table.setHorizontalHeaderLabels(["", "ID", "Name", "Train"])
        self.material_table.verticalHeader().setVisible(False)
        self.material_table.setShowGrid(False)
        self.material_table.setAlternatingRowColors(True)
        self.material_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.material_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.material_table.horizontalHeader().setStretchLastSection(True)
        self.current_material_swatch = QLabel("")
        self.current_material_swatch.setObjectName("tifCurrentMaterialSwatch")
        self.current_material_swatch.setFixedSize(34, 34)
        self.current_material_swatch.setToolTip("#000000")
        self.current_material_label = QLabel("")
        self.current_material_label.setObjectName("tifCurrentMaterialText")
        self.current_material_label.setWordWrap(True)
        self.current_material_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.btn_add_material = QPushButton("Add material")
        self.btn_edit_material = QPushButton("Edit material")
        self.btn_delete_material = QPushButton("Delete material")
        self.material_editor_buttons = QWidget()
        self.material_editor_buttons.setObjectName("tifMaterialEditorButtons")

        self.label_schema_combo = WheelSafeComboBox()
        self.label_schema_combo.setObjectName("tifLabelSchemaCombo")
        self.label_schema_combo.currentIndexChanged.connect(self._on_label_schema_selected)
        self.label_schema_id_edit = QLineEdit()
        self.label_schema_id_edit.setObjectName("tifLabelSchemaIdEdit")
        self.label_schema_part_name_edit = QLineEdit()
        self.label_schema_part_name_edit.setObjectName("tifLabelSchemaPartNameEdit")
        self.label_schema_table = QTableWidget(0, 4)
        self.label_schema_table.setObjectName("tifLabelSchemaTable")
        self.label_schema_table.setMinimumHeight(130)
        self.label_schema_table.setMaximumHeight(220)
        self.label_schema_table.setAlternatingRowColors(True)
        self.label_schema_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.label_schema_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.label_schema_table.verticalHeader().setVisible(False)
        self.label_schema_table.setShowGrid(False)
        self.label_schema_table.horizontalHeader().setStretchLastSection(True)
        self.label_schema_table.itemChanged.connect(self._on_label_schema_table_item_changed)
        self.label_schema_table.cellDoubleClicked.connect(self._on_label_schema_table_cell_double_clicked)
        self.label_schema_table.itemSelectionChanged.connect(self._on_label_schema_row_selected)
        self.btn_new_label_schema = QPushButton("New schema")
        self.btn_new_label_schema.setObjectName("tifNewLabelSchemaButton")
        self.btn_new_label_schema.clicked.connect(self.new_label_schema)
        self.btn_save_label_schema = QPushButton("Save schema")
        self.btn_save_label_schema.setObjectName("tifSaveLabelSchemaButton")
        self.btn_save_label_schema.clicked.connect(self.save_current_label_schema)
        self.btn_bind_label_schema_to_part = QPushButton("Bind to current part")
        self.btn_bind_label_schema_to_part.setObjectName("tifBindLabelSchemaToPartButton")
        self.btn_bind_label_schema_to_part.clicked.connect(self.bind_current_part_label_schema)
        self.btn_add_label_schema_row = QPushButton("Add region label")
        self.btn_add_label_schema_row.setObjectName("tifAddLabelSchemaRowButton")
        self.btn_add_label_schema_row.clicked.connect(self.add_label_schema_row)
        self.btn_remove_label_schema_row = QPushButton("Remove region label")
        self.btn_remove_label_schema_row.setObjectName("tifRemoveLabelSchemaRowButton")
        self.btn_remove_label_schema_row.clicked.connect(self.remove_selected_label_schema_row)
        self.btn_import_label_schema = QPushButton("Import schema")
        self.btn_import_label_schema.setObjectName("tifImportLabelSchemaButton")
        self.btn_import_label_schema.clicked.connect(self.import_label_schema_dialog)
        self.btn_export_label_schema = QPushButton("Export schema")
        self.btn_export_label_schema.setObjectName("tifExportLabelSchemaButton")
        self.btn_export_label_schema.clicked.connect(self.export_label_schema_dialog)

        self.part_user_tag_table = QTableWidget(0, 5)
        self.part_user_tag_table.setObjectName("tifPartUserTagTable")
        self.part_user_tag_table.setMinimumHeight(130)
        self.part_user_tag_table.setMaximumHeight(220)
        self.part_user_tag_table.setAlternatingRowColors(True)
        self.part_user_tag_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.part_user_tag_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.part_user_tag_table.setDragDropMode(QAbstractItemView.InternalMove)
        self.part_user_tag_table.setDragEnabled(True)
        self.part_user_tag_table.setAcceptDrops(True)
        self.part_user_tag_table.setDropIndicatorShown(True)
        self.part_user_tag_table.setDefaultDropAction(Qt.MoveAction)
        self.part_user_tag_table.verticalHeader().setVisible(False)
        self.part_user_tag_table.setShowGrid(False)
        self.part_user_tag_table.horizontalHeader().setStretchLastSection(True)
        self.part_user_tag_table.itemSelectionChanged.connect(self._on_part_user_tag_selected)
        try:
            self.part_user_tag_table.model().rowsMoved.connect(lambda *args: QTimer.singleShot(0, self.save_part_user_tag_order_from_table))
        except Exception:
            pass
        self.part_user_tag_id_edit = QLineEdit()
        self.part_user_tag_id_edit.setObjectName("tifPartUserTagIdEdit")
        self.part_user_tag_label_edit = QLineEdit()
        self.part_user_tag_label_edit.setObjectName("tifPartUserTagLabelEdit")
        self.part_user_tag_color_edit = QLineEdit("#6B8AFD")
        self.part_user_tag_color_edit.setObjectName("tifPartUserTagColorEdit")
        self.part_user_tag_color_swatch = QLabel("")
        self.part_user_tag_color_swatch.setObjectName("tifPartUserTagColorSwatch")
        self.part_user_tag_color_swatch.setFixedSize(34, 26)
        self.part_user_tag_color_edit.textChanged.connect(self._update_part_user_tag_color_swatch)
        self.part_user_tag_color_edit.setVisible(False)
        self._selected_part_user_tag_id_for_edit = ""
        self.btn_choose_part_user_tag_color = QPushButton("Choose group color")
        self.btn_choose_part_user_tag_color.setObjectName("tifChoosePartUserTagColorButton")
        self.btn_choose_part_user_tag_color.clicked.connect(self.choose_part_user_tag_color)
        self.btn_new_part_user_tag = QPushButton("Add group tag")
        self.btn_new_part_user_tag.setObjectName("tifNewPartUserTagButton")
        self.btn_new_part_user_tag.clicked.connect(self.new_part_user_tag)
        self.btn_save_part_user_tag = QPushButton("Save group tag")
        self.btn_save_part_user_tag.setObjectName("tifSavePartUserTagButton")
        self.btn_save_part_user_tag.clicked.connect(self.save_part_user_tag)
        self.btn_delete_part_user_tag = QPushButton("Delete group tag")
        self.btn_delete_part_user_tag.setObjectName("tifDeletePartUserTagButton")
        self.btn_delete_part_user_tag.clicked.connect(self.delete_selected_part_user_tag)
        self.btn_move_part_user_tag_up = QPushButton("Move up")
        self.btn_move_part_user_tag_up.setObjectName("tifMovePartUserTagUpButton")
        self.btn_move_part_user_tag_up.clicked.connect(lambda: self.move_selected_part_user_tag(-1))
        self.btn_move_part_user_tag_down = QPushButton("Move down")
        self.btn_move_part_user_tag_down.setObjectName("tifMovePartUserTagDownButton")
        self.btn_move_part_user_tag_down.clicked.connect(lambda: self.move_selected_part_user_tag(1))
        self.btn_apply_part_user_tags = QPushButton("Apply tags to current part")
        self.btn_apply_part_user_tags.setObjectName("tifApplyPartUserTagsButton")
        self.btn_apply_part_user_tags.clicked.connect(self.apply_part_user_tags_to_current_part)

        self.annotation_tool_label = QLabel("Tool")
        self.current_material_title_label = QLabel("Current label")
        self.btn_tool_brush = QPushButton("Brush")
        self.btn_tool_brush.setObjectName("tifToolBrushButton")
        self.btn_tool_brush.setCheckable(True)
        self.btn_tool_eraser = QPushButton("Eraser")
        self.btn_tool_eraser.setObjectName("tifToolEraserButton")
        self.btn_tool_eraser.setCheckable(True)
        self.btn_tool_lasso = QPushButton("Lasso fill")
        self.btn_tool_lasso.setObjectName("tifToolLassoButton")
        self.btn_tool_lasso.setCheckable(True)
        self.btn_tool_rectangle = QPushButton("Rectangle fill")
        self.btn_tool_rectangle.setObjectName("tifToolRectangleButton")
        self.btn_tool_rectangle.setCheckable(True)
        self.btn_tool_ellipse = QPushButton("Ellipse fill")
        self.btn_tool_ellipse.setObjectName("tifToolEllipseButton")
        self.btn_tool_ellipse.setCheckable(True)
        self.btn_interpolate_current_label = QPushButton("Interpolate fill")
        self.btn_interpolate_current_label.setObjectName("tifInterpolateCurrentLabelButton")
        self.btn_tool_picker = QPushButton("Picker")
        self.btn_tool_picker.setObjectName("tifToolPickerButton")
        self.btn_tool_picker.setCheckable(True)
        self.btn_tool_pan = QPushButton("Pan/view")
        self.btn_tool_pan.setObjectName("tifToolPanButton")
        self.btn_tool_pan.setCheckable(True)

        self.brush_size_slider = WheelSafeSlider(Qt.Horizontal)
        self.brush_size_slider.setRange(1, 80)
        self.brush_size_slider.setValue(8)
        self.btn_undo = QPushButton("Undo")
        self.btn_redo = QPushButton("Redo")
        self.btn_save_edit = QPushButton("Save current labels")
        self.auto_save_check = QCheckBox("Auto-save labels")
        self.auto_save_check.setObjectName("tifAutoSaveEditCheck")
        self.auto_save_check.setChecked(True)
        self.auto_save_hint_label = QLabel("")
        self.auto_save_hint_label.setObjectName("tifAutoSaveHintText")
        self.auto_save_hint_label.setWordWrap(True)
        self.save_status_title_label = QLabel("Save status")
        self.save_status_label = QLabel("")
        self.save_status_label.setObjectName("tifSaveStatusText")
        self.save_status_label.setWordWrap(True)
        self.save_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.btn_promote = QPushButton("Accept as training truth")
        self.btn_accept_selected_ai_results = QPushButton("Accept selected AI results")
        self.btn_accept_selected_ai_results.setObjectName("tifAcceptSelectedAiResultsButton")
        self.btn_copy_draft = QPushButton("Copy legacy model draft to current labels")
        self.btn_copy_draft.clicked.connect(self.copy_latest_model_draft_to_working_edit)
        self.btn_copy_draft.setVisible(False)
        self.btn_copy_material_prev = QPushButton("Copy label to previous slice")
        self.btn_copy_material_prev.setObjectName("tifCopyMaterialPrevButton")
        self.btn_copy_material_next = QPushButton("Copy label to next slice")
        self.btn_copy_material_next.setObjectName("tifCopyMaterialNextButton")
        self.btn_clear_current_material = QPushButton("Clear current label")
        self.btn_clear_current_material.setObjectName("tifClearCurrentMaterialButton")
        self.btn_import_tif = QPushButton("Import TIF stack")
        self.btn_import_tif.setObjectName("tifImportStackButton")
        self.btn_import_tif.clicked.connect(self.import_tif_stack_dialog)
        self.btn_import_amira = QPushButton("Import AMIRA directory")
        self.btn_import_amira.setObjectName("tifImportAmiraButton")
        self.btn_import_amira.clicked.connect(self.import_amira_directory_dialog)
        self.part_bbox_edit = QLineEdit()
        self.part_bbox_edit.setObjectName("tifPartBboxEdit")
        self.part_bbox_edit.setPlaceholderText("z0,z1,y0,y1,x0,x1")
        self.btn_part_draw_roi = QPushButton("Draw ROI")
        self.btn_part_draw_roi.setObjectName("tifPartDrawRoiButton")
        self.btn_part_draw_roi.setCheckable(True)
        self.btn_save_part_roi = QPushButton("Save ROI draft")
        self.btn_save_part_roi.setObjectName("tifSavePartRoiButton")
        self.btn_confirm_part_roi = QPushButton("Confirm ROI")
        self.btn_confirm_part_roi.setObjectName("tifConfirmPartRoiButton")
        self.btn_cancel_part_roi = QPushButton("Cancel ROI")
        self.btn_cancel_part_roi.setObjectName("tifCancelPartRoiButton")
        self.btn_create_part = QPushButton("Create part")
        self.btn_create_part.setObjectName("tifCreatePartButton")
        self.btn_create_part.clicked.connect(self.create_part_from_bbox_dialog)
        self.btn_add_rect_keyframe = QPushButton("Add rectangular key slice")
        self.btn_add_rect_keyframe.setObjectName("tifAddRectKeyframeButton")
        self.btn_draw_part_contour = QPushButton("Draw contour")
        self.btn_draw_part_contour.setObjectName("tifDrawPartContourButton")
        self.btn_draw_part_contour.setCheckable(True)
        self.btn_delete_part_contour = QPushButton("Delete key slice")
        self.btn_delete_part_contour.setObjectName("tifDeletePartContourButton")
        self.btn_clear_part_keyframes = QPushButton("Clear key slices")
        self.btn_clear_part_keyframes.setObjectName("tifClearPartKeyframesButton")
        self.btn_prev_key_slice = QPushButton("Previous key slice")
        self.btn_prev_key_slice.setObjectName("tifPrevPartKeySliceButton")
        self.btn_next_key_slice = QPushButton("Next key slice")
        self.btn_next_key_slice.setObjectName("tifNextPartKeySliceButton")
        self.btn_preview_part_mask = QPushButton("Preview auto fill")
        self.btn_preview_part_mask.setObjectName("tifPreviewPartMaskButton")
        self.btn_accept_part_mask = QPushButton("Accept part mask")
        self.btn_accept_part_mask.setObjectName("tifAcceptPartMaskButton")
        self.btn_clear_part_preview = QPushButton("Clear preview")
        self.btn_clear_part_preview.setObjectName("tifClearPartPreviewButton")
        self.btn_local_axis_reslice = QPushButton("Export confirmed reslice")
        self.btn_local_axis_reslice.setObjectName("tifLocalAxisResliceButton")
        self.btn_copy_source_z_axis = QPushButton("Copy source Z axis")
        self.btn_copy_source_z_axis.setObjectName("tifCopySourceZAxisButton")
        self.btn_pick_roll_ref_a = QPushButton("Pick roll reference A")
        self.btn_pick_roll_ref_a.setObjectName("tifPickRollReferenceAButton")
        self.btn_pick_roll_ref_a.setCheckable(True)
        self.btn_pick_roll_ref_b = QPushButton("Pick roll reference B")
        self.btn_pick_roll_ref_b.setObjectName("tifPickRollReferenceBButton")
        self.btn_pick_roll_ref_b.setCheckable(True)
        self.btn_pick_roll_ref_c = QPushButton("Pick plane reference C")
        self.btn_pick_roll_ref_c.setObjectName("tifPickPlaneReferenceCButton")
        self.btn_pick_roll_ref_c.setCheckable(True)
        self.btn_align_axis_to_reference_plane = QPushButton("Make Z perpendicular\nto A/B/C plane")
        self.btn_align_axis_to_reference_plane.setObjectName("tifAlignAxisToReferencePlaneButton")
        self.btn_clear_roll_refs = QPushButton("Clear roll refs")
        self.btn_clear_roll_refs.setObjectName("tifClearRollRefsButton")
        self.btn_clear_local_axis_draft = QPushButton("Clear axis draft")
        self.btn_clear_local_axis_draft.setObjectName("tifClearLocalAxisDraftButton")
        self.local_axis_trainable_check = QCheckBox("Record this export as trainable local-axis data")
        self.local_axis_trainable_check.setObjectName("tifLocalAxisTrainableCheck")
        self.local_axis_trainable_check.setChecked(True)
        self.btn_export_local_axis_training_manifest = QPushButton("Export confirmed Local Axis training manifest")
        self.btn_export_local_axis_training_manifest.setObjectName("tifExportLocalAxisTrainingManifestButton")
        self.btn_export_part_package = QPushButton("Export part package")
        self.btn_export_part_package.setObjectName("tifExportPartPackageButton")
        self.btn_export_part_package.clicked.connect(self.export_current_part_package)
        self.btn_export_reviewed_mesh = QPushButton("Export reviewed label STL")
        self.btn_export_reviewed_mesh.setObjectName("tifExportReviewedMeshButton")
        self.btn_export_reviewed_mesh.clicked.connect(self.open_reviewed_mesh_export_dialog)
        self.btn_delete_part_volume = QPushButton("Delete part volume")
        self.btn_delete_part_volume.setObjectName("tifDeletePartVolumeButton")
        self.btn_delete_part_volume.clicked.connect(self.delete_current_part_volume)
        self.btn_export_training = QPushButton("Export train-ready volumes")
        self.btn_export_training.setObjectName("tifExportTrainingButton")
        self.btn_export_training.clicked.connect(self.export_training_dataset)
        self.backend_id_edit = QLineEdit()
        self.backend_id_edit.setObjectName("tifBackendIdEdit")
        self.backend_display_edit = QLineEdit()
        self.backend_python_edit = QLineEdit()
        self.backend_formats_edit = QLineEdit()
        self.backend_prepare_edit = QLineEdit()
        self.backend_train_edit = QLineEdit()
        self.backend_predict_edit = QLineEdit()
        self.backend_manifest_edit = QLineEdit()
        self.btn_browse_model_manifest = QPushButton("Browse manifest")
        self.btn_browse_model_manifest.setObjectName("tifBrowseModelManifestButton")
        self.btn_use_nnunet_backend_preset = QPushButton("Use nnU-Net v2 preset")
        self.btn_use_nnunet_backend_preset.setObjectName("tifUseNnunetV2PresetButton")
        self.btn_save_backend = QPushButton("Save backend settings")
        self.btn_save_backend.setObjectName("tifSaveBackendButton")
        self.btn_prepare_dataset = QPushButton("Prepare dataset")
        self.btn_prepare_dataset.setObjectName("tifPrepareDatasetButton")
        self.btn_train_backend = QPushButton("Train backend")
        self.btn_train_backend.setObjectName("tifTrainBackendButton")
        self.btn_import_prediction = QPushButton("Import prediction")
        self.btn_import_prediction.setObjectName("tifImportPredictionButton")
        self.predict_filter_combo = WheelSafeComboBox()
        self.predict_filter_combo.setObjectName("tifPredictFilterCombo")
        self.predict_targets_table = QTableWidget(0, 8)
        self.predict_targets_table.setObjectName("tifPredictTargetsTable")
        self.predict_targets_table.setMinimumHeight(150)
        self.predict_targets_table.setMaximumHeight(260)
        self.predict_targets_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.predict_targets_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.predict_targets_table.setAlternatingRowColors(True)
        self.predict_targets_table.verticalHeader().setVisible(False)
        self.predict_targets_table.setShowGrid(False)
        self.predict_targets_table.horizontalHeader().setStretchLastSection(True)
        self.btn_refresh_predict_targets = QPushButton("Refresh targets")
        self.btn_refresh_predict_targets.setObjectName("tifRefreshPredictTargetsButton")
        self.btn_select_current_predict_target = QPushButton("Select current part")
        self.btn_select_current_predict_target.setObjectName("tifSelectCurrentPredictTargetButton")
        self.btn_select_ready_predict_targets = QPushButton("Select all ready")
        self.btn_select_ready_predict_targets.setObjectName("tifSelectReadyPredictTargetsButton")
        self.btn_clear_predict_targets = QPushButton("Clear selection")
        self.btn_clear_predict_targets.setObjectName("tifClearPredictTargetsButton")
        self.predict_targets_summary_label = QLabel("")
        self.predict_targets_summary_label.setObjectName("tifPredictTargetsSummaryText")
        self.predict_targets_summary_label.setWordWrap(True)
        self.predict_targets_summary_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.btn_stop_backend = QPushButton("Stop run")
        self.btn_stop_backend.setObjectName("tifStopBackendButton")
        self.btn_stop_backend.setEnabled(False)
        self.btn_open_backend_run = QPushButton("Open run folder")
        self.btn_open_backend_run.setObjectName("tifOpenBackendRunButton")
        self.btn_open_backend_run.setEnabled(False)
        self.btn_open_backend_result = QPushButton("Open result JSON")
        self.btn_open_backend_result.setObjectName("tifOpenBackendResultButton")
        self.btn_open_backend_result.setEnabled(False)
        self.training_result_summary_label = QLabel("No training result yet.")
        self.training_result_summary_label.setObjectName("tifTrainingResultSummaryText")
        self.training_result_summary_label.setWordWrap(True)
        self.training_result_summary_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.training_result_summary_label.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.btn_show_training_result_summary = QPushButton("Show result summary")
        self.btn_show_training_result_summary.setObjectName("tifShowTrainingResultSummaryButton")
        self.btn_show_training_result_summary.setEnabled(False)
        self.btn_open_training_model_output = QPushButton("Open model output")
        self.btn_open_training_model_output.setObjectName("tifOpenTrainingModelOutputButton")
        self.btn_open_training_model_output.setEnabled(False)
        self.btn_open_training_model_manifest = QPushButton("Open model manifest")
        self.btn_open_training_model_manifest.setObjectName("tifOpenTrainingModelManifestButton")
        self.btn_open_training_model_manifest.setEnabled(False)
        self.btn_batch_predict_entry = QPushButton("Enter batch prediction")
        self.btn_batch_predict_entry.setObjectName("tifBatchPredictEntryButton")
        self.btn_batch_predict_entry.setEnabled(False)
        self.model_library_combo = WheelSafeComboBox()
        self.model_library_combo.setObjectName("tifModelLibraryCombo")
        self.model_library_notes_edit = QTextEdit()
        self.model_library_notes_edit.setObjectName("tifModelLibraryNotesEdit")
        self.model_library_notes_edit.setPlaceholderText("Model notes")
        self.model_library_notes_edit.setMinimumHeight(58)
        self.model_library_notes_edit.setMaximumHeight(86)
        self.model_library_notes_edit.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.model_library_summary_label = QLabel("")
        self.model_library_summary_label.setObjectName("tifModelLibrarySummaryText")
        self.model_library_summary_label.setWordWrap(True)
        self.model_library_summary_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.btn_use_selected_tif_model = QPushButton("Use selected model")
        self.btn_use_selected_tif_model.setObjectName("tifUseSelectedModelButton")
        self.btn_use_selected_tif_model.clicked.connect(self.use_selected_tif_model)
        self.btn_save_tif_model_notes = QPushButton("Save notes")
        self.btn_save_tif_model_notes.setObjectName("tifSaveModelNotesButton")
        self.btn_save_tif_model_notes.clicked.connect(self.save_selected_tif_model_notes)
        self.btn_delete_tif_model_record = QPushButton("Delete registration")
        self.btn_delete_tif_model_record.setObjectName("tifDeleteModelRecordButton")
        self.btn_delete_tif_model_record.clicked.connect(self.delete_selected_tif_model_record)
        self.btn_import_external_prediction_tif = QPushButton("Import external label TIF as review result")
        self.btn_import_external_prediction_tif.setObjectName("tifImportExternalPredictionTifButton")
        self.result_source_manual_radio = QRadioButton("manual_truth")
        self.result_source_manual_radio.setObjectName("tifResultSourceManualTruthRadio")
        self.result_source_manual_radio.setChecked(True)
        self.result_source_editable_radio = QRadioButton("editable_ai_result")
        self.result_source_editable_radio.setObjectName("tifResultSourceEditableAiRadio")
        self.result_region_combo = WheelSafeComboBox()
        self.result_region_combo.setObjectName("tifResultRegionCombo")
        self.result_compare_table = QTableWidget(0, 8)
        self.result_compare_table.setObjectName("tifResultComparisonTable")
        self.result_compare_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.result_compare_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.result_compare_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.result_compare_table.setAlternatingRowColors(True)
        self.result_compare_table.setShowGrid(False)
        self.result_compare_table.horizontalHeader().setStretchLastSection(True)
        self.btn_refresh_result_comparison = QPushButton("Refresh comparison")
        self.btn_refresh_result_comparison.setObjectName("tifRefreshResultComparisonButton")
        self.btn_open_result_comparison_target = QPushButton("Open selected in 3D")
        self.btn_open_result_comparison_target.setObjectName("tifOpenResultComparisonTargetButton")
        self.btn_show_result_region_in_3d = QPushButton("Highlight selected region")
        self.btn_show_result_region_in_3d.setObjectName("tifShowResultRegionIn3DButton")
        self.result_compare_summary_label = QLabel("")
        self.result_compare_summary_label.setObjectName("tifResultComparisonSummaryText")
        self.result_compare_summary_label.setWordWrap(True)
        self.result_compare_summary_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.btn_export_current_rendering = QPushButton("Export current rendering screenshot")
        self.btn_export_current_rendering.setObjectName("tifExportCurrentRenderingButton")
        self.btn_export_current_rendering.clicked.connect(self.export_current_rendering_screenshot)
        self.btn_start_center = QPushButton("Start Center")
        self.btn_start_center.setObjectName("tifStartCenterButton")
        self.btn_ask_agent = QPushButton("Ask Agent")
        self.btn_ask_agent.setObjectName("tifAskAgentButton")
        self.btn_show_workbench_log = QPushButton("Workbench log")
        self.btn_show_workbench_log.setObjectName("tifShowWorkbenchLogButton")
        self.operation_status_label = QLabel("")
        self.operation_status_label.setObjectName("tifOperationStatusText")
        self.operation_status_label.setWordWrap(True)
        self.operation_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.training_status_label = MirroredStatusLabel("")
        self.training_status_label.setObjectName("tifTrainingStatusText")
        self.training_status_label.setWordWrap(True)
        self.training_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.training_status_label.set_mirror_label(self.operation_status_label)
        self.backend_run_status_label = QLabel("Idle")
        self.backend_run_status_label.setObjectName("tifBackendRunStatusText")
        self.backend_run_status_label.setWordWrap(True)
        self.backend_run_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.backend_run_status_label.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.backend_run_title_label = QLabel("Backend run")
        self.backend_run_title_label.setObjectName("tifSectionTitle")
        self.backend_elapsed_label = QLabel("Elapsed: 00:00")
        self.backend_elapsed_label.setObjectName("tifBackendElapsedText")
        self.backend_progress_bar = QProgressBar()
        self.backend_progress_bar.setObjectName("tifBackendProgressBar")
        self.backend_progress_bar.setRange(0, 100)
        self.backend_progress_bar.setValue(0)
        self.backend_progress_bar.setTextVisible(True)
        self.backend_progress_bar.setFormat("%p%")
        self.backend_log_tail = QTextEdit()
        self.backend_log_tail.setObjectName("tifBackendLogTail")
        self.backend_log_tail.setReadOnly(True)
        self.backend_log_tail.setLineWrapMode(QTextEdit.WidgetWidth)
        self.backend_log_tail.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.backend_log_tail.setMinimumHeight(92)
        self.backend_log_tail.setMaximumHeight(132)
        self.backend_elapsed_timer = QTimer(self)
        self.backend_elapsed_timer.setInterval(1000)
        self.backend_elapsed_timer.timeout.connect(self._update_backend_elapsed_label)
        self.log_console = QTextEdit()
        self.log_console.setObjectName("tifLogConsole")
        self.log_console.setReadOnly(True)
        self.log_console.setMinimumHeight(90)
        self.log_console.setMaximumHeight(140)
        self.shortcut_undo = QShortcut(QKeySequence("Ctrl+Z"), self)
        self.shortcut_redo = QShortcut(QKeySequence("Ctrl+Y"), self)
        self.shortcut_redo_alt = QShortcut(QKeySequence("Ctrl+Shift+Z"), self)
        self.shortcut_save_edit = QShortcut(QKeySequence("Ctrl+S"), self)
        self.shortcut_tool_brush = QShortcut(QKeySequence("B"), self)
        self.shortcut_tool_eraser = QShortcut(QKeySequence("E"), self)
        self.shortcut_tool_lasso = QShortcut(QKeySequence("L"), self)
        self.shortcut_tool_rectangle = QShortcut(QKeySequence("R"), self)
        self.shortcut_tool_ellipse = QShortcut(QKeySequence("O"), self)
        self.shortcut_tool_picker = QShortcut(QKeySequence("I"), self)
        self.shortcut_brush_smaller = QShortcut(QKeySequence("["), self)
        self.shortcut_brush_larger = QShortcut(QKeySequence("]"), self)
        self.auto_save_timer = QTimer(self)
        self.auto_save_timer.setSingleShot(True)
        self.auto_save_timer.setInterval(1200)
        self.auto_save_timer.timeout.connect(lambda: self.annotation_workflow_controller.start_auto_save(reason="auto_save"))
        self.volume_still_timer = QTimer(self)
        self.volume_still_timer.setSingleShot(True)
        self.volume_still_timer.setInterval(220)

    def build_layout(self):
        self = self.workbench
        self._field_labels = {}
        root = QVBoxLayout(self)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(10)

        top_bar = QFrame()
        top_bar.setObjectName("tifWorkbenchTopBar")
        top_layout = QHBoxLayout(top_bar)
        top_layout.setContentsMargins(12, 8, 12, 8)
        top_layout.setSpacing(8)
        self.tif_top_context_label = QLabel("TIF Volume Workbench")
        self.tif_top_context_label.setObjectName("tifTopContextLabel")
        top_layout.addWidget(self.tif_top_context_label, 1)
        top_layout.addWidget(self.btn_start_center)
        top_layout.addWidget(self.btn_ask_agent)
        root.addWidget(top_bar)

        splitter = QSplitter(Qt.Horizontal)
        splitter.setObjectName("tifWorkbenchSplitter")
        root.addWidget(splitter, 1)

        left, left_layout = self._make_panel("Specimens", "tifSpecimenPanel")
        left_layout.addWidget(self.specimen_list, 1)
        splitter.addWidget(left)

        center, center_layout = self._make_panel("Volume slices", "tifVolumePanel")
        canvas_shell = QFrame()
        canvas_shell.setObjectName("tifCanvasShell")
        canvas_layout = QVBoxLayout(canvas_shell)
        canvas_layout.setContentsMargins(6, 6, 6, 6)
        self.view_stack = QStackedWidget()
        self.view_stack.setObjectName("tifViewStack")
        self.view_stack.addWidget(self.canvas)
        self.view_stack.addWidget(self.volume_canvas)
        canvas_layout.addWidget(self.view_stack, 1)
        canvas_layout.addWidget(self.volume_render_status_label)
        center_layout.addWidget(canvas_shell, 1)
        slice_bar = QFrame()
        slice_bar.setObjectName("tifSliceBar")
        slice_row = QHBoxLayout()
        slice_row.setContentsMargins(10, 6, 10, 6)
        self.display_mode_label = QLabel("Display mode")
        slice_row.addWidget(self.display_mode_combo)
        slice_row.addWidget(self.display_mode_label)
        self.slice_axis_label = QLabel("View plane")
        slice_row.addWidget(self.slice_axis_label)
        slice_row.addWidget(self.slice_axis_combo)
        slice_row.addWidget(self.slice_prefix_label)
        slice_row.addWidget(self.slice_slider, 1)
        slice_row.addWidget(self.slice_label)
        slice_bar.setLayout(slice_row)
        center_layout.addWidget(slice_bar)
        splitter.addWidget(center)

        if not hasattr(self, "_panel_title_labels"):
            self._panel_title_labels = {}
        if not hasattr(self, "_section_title_labels"):
            self._section_title_labels = {}
        right_panel_parts = build_right_control_panel(self._panel_title_labels, self._section_title_labels)
        right = right_panel_parts["panel"]
        right_layout = right_panel_parts["layout"]
        self.operation_status_section = right_panel_parts["operation_status_section"]
        operation_status_layout = right_panel_parts["operation_status_layout"]
        operation_status_layout.addWidget(self.operation_status_label)
        operation_status_layout.addWidget(self.btn_show_workbench_log)
        right_layout.addWidget(self.operation_status_section)

        task_page_parts = build_task_pages(self.lang, tt)
        self.task_tabs = task_page_parts["task_tabs"]
        self.training_mode_tabs = task_page_parts["training_mode_tabs"]
        self.part_task_page = task_page_parts["part_task_page"]
        self.part_task_layout = task_page_parts["part_task_layout"]
        self.display_task_page = task_page_parts["display_task_page"]
        self.display_task_layout = task_page_parts["display_task_layout"]
        self.annotation_task_page = task_page_parts["annotation_task_page"]
        self.annotation_task_layout = task_page_parts["annotation_task_layout"]
        self.training_task_page = task_page_parts["training_task_page"]
        self.training_task_layout = task_page_parts["training_task_layout"]
        self.result_compare_page = task_page_parts["result_compare_page"]
        self.result_compare_layout = task_page_parts["result_compare_layout"]
        right_layout.addWidget(self.task_tabs, 1)
        self.task_tabs.currentChanged.connect(self.result_review_controller.on_training_mode_tab_changed)

        import_section, import_layout = self._make_section("Data import", "tifImportSection")
        import_button_row = QHBoxLayout()
        import_button_row.addWidget(self.btn_import_tif)
        import_button_row.addWidget(self.btn_import_amira)
        import_layout.addLayout(import_button_row)
        self.part_task_layout.addWidget(import_section)

        status_section, status_layout = self._make_section("Current object", "tifStatusSection")
        status_layout.addWidget(self.status_label)
        status_layout.addWidget(self.show_debug_paths_check)
        status_layout.addWidget(self.metadata_label)
        self.part_task_layout.addWidget(status_section)

        self.part_locate_section, part_locate_layout = self._make_section("1. Locate part", "tifPartLocateSection")
        part_locate_layout.addWidget(self.part_bbox_edit)
        part_bbox_row = QHBoxLayout()
        part_bbox_row.addWidget(self.btn_part_draw_roi)
        part_locate_layout.addLayout(part_bbox_row)
        part_draft_row = QHBoxLayout()
        part_draft_row.addWidget(self.btn_save_part_roi)
        part_draft_row.addWidget(self.btn_confirm_part_roi)
        part_locate_layout.addLayout(part_draft_row)
        part_action_row = QHBoxLayout()
        part_action_row.addWidget(self.btn_cancel_part_roi)
        part_locate_layout.addLayout(part_action_row)
        self.part_task_layout.addWidget(self.part_locate_section)

        self.part_mask_section, part_mask_layout = self._make_section("2. Build part mask", "tifPartMaskSection")
        part_key_row = QHBoxLayout()
        part_key_row.addWidget(self.btn_draw_part_contour)
        part_mask_layout.addLayout(part_key_row)
        part_key_nav_row = QHBoxLayout()
        part_key_nav_row.addWidget(self.btn_prev_key_slice)
        part_key_nav_row.addWidget(self.btn_next_key_slice)
        part_mask_layout.addLayout(part_key_nav_row)
        part_key_action_row = QHBoxLayout()
        part_key_action_row.addWidget(self.btn_delete_part_contour)
        part_key_action_row.addWidget(self.btn_clear_part_keyframes)
        part_key_action_row.addWidget(self.btn_preview_part_mask)
        part_mask_layout.addLayout(part_key_action_row)
        part_mask_row = QHBoxLayout()
        part_mask_row.addWidget(self.btn_accept_part_mask)
        part_mask_row.addWidget(self.btn_clear_part_preview)
        part_mask_layout.addLayout(part_mask_row)
        self.part_task_layout.addWidget(self.part_mask_section)

        self.local_axis_volume_section, local_axis_volume_layout = self._make_section(
            "Local Axis Reslice / part volume",
            "tifLocalAxisVolumeSection",
        )
        self.local_axis_volume_help_label = QLabel(
            tt(
                "Roll A/B/C picking works on the observation-side clip plane only. Turn on Clip plane in the 3D preview, move it to the target cross-section, then click A, B, and C on that plane.",
                self.lang,
            )
        )
        self.local_axis_volume_help_label.setObjectName("tifLayerHelpText")
        self.local_axis_volume_help_label.setWordWrap(True)
        local_axis_volume_layout.addWidget(self.local_axis_volume_help_label)
        local_axis_display_row = QHBoxLayout()
        local_axis_display_row.addWidget(self.volume_local_axes_check)
        local_axis_display_row.addStretch(1)
        local_axis_volume_layout.addLayout(local_axis_display_row)
        local_axis_volume_layout.addWidget(self.local_axis_status_label)
        local_axis_volume_layout.addWidget(self.local_axis_summary_label)
        local_axis_volume_layout.addWidget(self.local_axis_details_check)
        local_axis_volume_layout.addWidget(self.local_axis_details_label)
        local_axis_volume_row = QHBoxLayout()
        local_axis_volume_row.addWidget(self.btn_copy_source_z_axis)
        local_axis_volume_row.addWidget(self.btn_local_axis_reslice)
        local_axis_volume_layout.addLayout(local_axis_volume_row)
        local_axis_roll_grid = QGridLayout()
        local_axis_roll_grid.setHorizontalSpacing(8)
        local_axis_roll_grid.setVerticalSpacing(8)
        local_axis_roll_grid.addWidget(self.btn_pick_roll_ref_a, 0, 0)
        local_axis_roll_grid.addWidget(self.btn_pick_roll_ref_b, 0, 1)
        local_axis_roll_grid.addWidget(self.btn_pick_roll_ref_c, 1, 0)
        local_axis_roll_grid.addWidget(self.btn_clear_roll_refs, 1, 1)
        local_axis_roll_grid.setColumnStretch(0, 1)
        local_axis_roll_grid.setColumnStretch(1, 1)
        local_axis_volume_layout.addLayout(local_axis_roll_grid)
        local_axis_plane_row = QHBoxLayout()
        local_axis_plane_row.addWidget(self.btn_align_axis_to_reference_plane)
        local_axis_volume_layout.addLayout(local_axis_plane_row)
        local_axis_center_row = QHBoxLayout()
        local_axis_center_row.addWidget(self.btn_clear_local_axis_draft)
        local_axis_volume_layout.addLayout(local_axis_center_row)
        local_axis_volume_layout.addWidget(self.local_axis_trainable_check)
        local_axis_volume_layout.addWidget(self.btn_export_local_axis_training_manifest)
        self.part_task_layout.addWidget(self.local_axis_volume_section)

        self.part_output_section, part_output_layout = self._make_section("3. Output and manage", "tifPartOutputSection")
        part_output_layout.addWidget(self.btn_export_part_package)
        part_output_layout.addWidget(self.btn_export_reviewed_mesh)
        part_output_layout.addWidget(self.btn_delete_part_volume)
        self.part_task_layout.addWidget(self.part_output_section)

        self.slice_display_section, slice_display_layout = self._make_section("Slice display", "tifSliceDisplaySection")
        slice_controls = QGridLayout()
        slice_controls.setHorizontalSpacing(10)
        slice_controls.setVerticalSpacing(8)
        self.label_layer_label = QLabel("Label layer")
        self.overlay_label = QLabel("Overlay")
        self.brightness_label = QLabel("Brightness")
        self.contrast_label = QLabel("Contrast")
        slice_controls.addWidget(self.overlay_label, 0, 0)
        slice_controls.addWidget(self.opacity_slider, 0, 1)
        slice_controls.addWidget(self.brightness_label, 1, 0)
        slice_controls.addWidget(self.brightness_slider, 1, 1)
        slice_controls.addWidget(self.contrast_label, 2, 0)
        slice_controls.addWidget(self.contrast_slider, 2, 1)
        slice_display_layout.addLayout(slice_controls)
        self.display_task_layout.addWidget(self.slice_display_section)

        self.volume_render_section, volume_render_layout = self._make_section("3D rendering", "tifVolumeRenderSection")
        volume_controls = QGridLayout()
        volume_controls.setHorizontalSpacing(10)
        volume_controls.setVerticalSpacing(8)
        self.volume_projection_label = QLabel("Render mode")
        self.volume_tint_label = QLabel("Transfer function")
        self.volume_enhancement_label = QLabel("Detail enhancement")
        self.volume_tone_label = QLabel("Tone curve")
        self.volume_mask_label = QLabel("Mask display")
        self.volume_mask_opacity_label = QLabel("Mask opacity")
        self.volume_cutoff_label = QLabel("Density cutoff")
        self.volume_quality_label = QLabel("Render quality")
        self.volume_sample_label = QLabel("Ray samples")
        self.volume_roi_scale_label = QLabel("ROI scale")
        self.volume_roi_budget_label = QLabel("ROI budget")
        self.volume_inside_label = QLabel("Inside depth")
        self.volume_clip_label = QLabel("Front cut")
        volume_controls.addWidget(self.volume_projection_label, 0, 0)
        volume_controls.addWidget(self.volume_projection_combo, 0, 1)
        volume_controls.addWidget(self.volume_tint_label, 1, 0)
        color_row = QHBoxLayout()
        color_row.addWidget(self.volume_tint_combo, 1)
        color_row.addWidget(self.btn_volume_custom_color)
        color_row.addWidget(self.btn_volume_morphology_preset)
        volume_controls.addLayout(color_row, 1, 1)
        self.volume_transfer_opacity_label = QLabel("Density opacity")
        volume_controls.addWidget(self.volume_transfer_opacity_label, 2, 0)
        volume_controls.addWidget(self.volume_transfer_opacity_slider, 2, 1)
        volume_controls.addWidget(self.volume_enhancement_label, 3, 0)
        volume_controls.addWidget(self.volume_enhancement_slider, 3, 1)
        volume_controls.addWidget(self.volume_tone_label, 4, 0)
        volume_controls.addWidget(self.volume_tone_slider, 4, 1)
        self.volume_shader_quality_label = QLabel("Shader quality")
        volume_controls.addWidget(self.volume_shader_quality_label, 5, 0)
        volume_controls.addWidget(self.volume_shader_quality_combo, 5, 1)
        volume_controls.addWidget(self.volume_mask_label, 6, 0)
        volume_controls.addWidget(self.volume_mask_combo, 6, 1)
        volume_controls.addWidget(self.volume_mask_opacity_label, 7, 0)
        volume_controls.addWidget(self.volume_mask_opacity_slider, 7, 1)
        volume_controls.addWidget(self.volume_cutoff_label, 8, 0)
        volume_controls.addWidget(self.volume_cutoff_slider, 8, 1)
        volume_controls.addWidget(self.volume_quality_label, 9, 0)
        volume_controls.addWidget(self.volume_quality_slider, 9, 1)
        volume_controls.addWidget(self.volume_sample_label, 10, 0)
        volume_controls.addWidget(self.volume_sample_slider, 10, 1)
        volume_controls.addWidget(self.volume_clarity_check, 11, 0, 1, 2)
        volume_controls.addWidget(self.volume_surface_refine_check, 12, 0, 1, 2)
        volume_controls.addWidget(self.volume_roi_detail_check, 13, 0, 1, 2)
        volume_controls.addWidget(self.volume_roi_source_combo, 14, 0, 1, 2)
        volume_controls.addWidget(self.volume_roi_inspect_check, 15, 0, 1, 2)
        volume_controls.addWidget(self.volume_roi_scale_label, 16, 0)
        volume_controls.addWidget(self.volume_roi_scale_slider, 16, 1)
        volume_controls.addWidget(self.volume_roi_budget_label, 17, 0)
        volume_controls.addWidget(self.volume_roi_budget_combo, 17, 1)
        volume_controls.addWidget(self.volume_clip_plane_check, 18, 0, 1, 2)
        volume_controls.addWidget(self.volume_clip_plane_depth_label, 19, 0)
        volume_controls.addWidget(self.volume_clip_plane_depth_slider, 19, 1)
        volume_controls.addWidget(self.volume_inside_label, 20, 0)
        volume_controls.addWidget(self.volume_inside_slider, 20, 1)
        volume_controls.addWidget(self.volume_clip_label, 21, 0)
        volume_controls.addWidget(self.volume_clip_slider, 21, 1)
        volume_render_layout.addLayout(volume_controls)
        volume_render_layout.addWidget(self.btn_reset_volume_view)
        self.display_task_layout.addWidget(self.volume_render_section)

        self.material_section, material_layout = self._make_section("Current labels", "tifMaterialSection")
        self.material_help_label = QLabel(tt("After binding a label schema, select one current label here before using the brush or fill tools.", self.lang))
        self.material_help_label.setObjectName("tifLayerHelpText")
        self.material_help_label.setWordWrap(True)
        material_layout.addWidget(self.material_help_label)
        current_material_row = QHBoxLayout()
        current_material_row.setSpacing(10)
        current_material_row.addWidget(self.current_material_swatch)
        current_material_text = QVBoxLayout()
        current_material_text.setSpacing(2)
        current_material_text.addWidget(self.current_material_title_label)
        current_material_text.addWidget(self.current_material_label)
        current_material_row.addLayout(current_material_text, 1)
        material_layout.addLayout(current_material_row)
        self.material_scope_help_label = QLabel(tt("Material IDs are the numeric labels stored in the current volume. For part volumes, this list follows the bound region label schema; for full volumes, it is the specimen material map.", self.lang))
        self.material_scope_help_label.setObjectName("tifLayerHelpText")
        self.material_scope_help_label.setWordWrap(True)
        material_layout.addWidget(self.material_scope_help_label)
        material_button_row = QHBoxLayout(self.material_editor_buttons)
        material_button_row.setContentsMargins(0, 0, 0, 0)
        material_button_row.setSpacing(6)
        material_button_row.addWidget(self.btn_add_material)
        material_button_row.addWidget(self.btn_edit_material)
        material_button_row.addWidget(self.btn_delete_material)
        material_layout.addWidget(self.material_editor_buttons)
        material_layout.addWidget(self.material_table)

        self.annotation_section, annotation_layout = self._make_section("Annotation tools", "tifAnnotationSection")
        controls = QGridLayout()
        controls.setHorizontalSpacing(10)
        controls.setVerticalSpacing(8)
        self.brush_size_label = QLabel("Brush size")
        tool_grid = QGridLayout()
        tool_grid.setHorizontalSpacing(6)
        tool_grid.setVerticalSpacing(6)
        tool_grid.addWidget(self.btn_tool_brush, 0, 0)
        tool_grid.addWidget(self.btn_tool_eraser, 0, 1)
        tool_grid.addWidget(self.btn_tool_lasso, 1, 0)
        tool_grid.addWidget(self.btn_tool_rectangle, 1, 1)
        tool_grid.addWidget(self.btn_tool_ellipse, 2, 0)
        tool_grid.addWidget(self.btn_tool_picker, 2, 1)
        tool_grid.addWidget(self.btn_interpolate_current_label, 3, 0, 1, 2)
        tool_grid.addWidget(self.btn_tool_pan, 4, 0, 1, 2)
        controls.addWidget(self.annotation_tool_label, 0, 0)
        controls.addLayout(tool_grid, 0, 1)
        controls.addWidget(self.label_layer_label, 1, 0)
        controls.addWidget(self.label_role_combo, 1, 1)
        controls.addWidget(self.brush_size_label, 2, 0)
        controls.addWidget(self.brush_size_slider, 2, 1)
        annotation_layout.addLayout(controls)
        annotation_layout.addWidget(self.label_role_help_label)
        annotation_layout.addWidget(self.ai_review_check_title_label)
        annotation_layout.addWidget(self.ai_review_check_label)
        button_row = QHBoxLayout()
        button_row.addWidget(self.btn_undo)
        button_row.addWidget(self.btn_redo)
        annotation_layout.addLayout(button_row)
        save_status_row = QHBoxLayout()
        save_status_row.setSpacing(8)
        save_status_row.addWidget(self.save_status_title_label)
        save_status_row.addWidget(self.save_status_label, 1)
        annotation_layout.addLayout(save_status_row)
        auto_save_row = QHBoxLayout()
        auto_save_row.setSpacing(8)
        auto_save_row.addWidget(self.auto_save_check)
        auto_save_row.addWidget(self.auto_save_hint_label, 1)
        annotation_layout.addLayout(auto_save_row)
        annotation_layout.addWidget(self.btn_save_edit)
        slice_helper_row = QHBoxLayout()
        slice_helper_row.setSpacing(6)
        slice_helper_row.addWidget(self.btn_copy_material_prev)
        slice_helper_row.addWidget(self.btn_copy_material_next)
        annotation_layout.addLayout(slice_helper_row)
        annotation_layout.addWidget(self.btn_clear_current_material)
        annotation_layout.addWidget(self.btn_promote)
        annotation_layout.addWidget(self.btn_copy_draft)

        self.label_schema_section, label_schema_layout = self._make_section("Region label schema", "tifLabelSchemaSection")
        self.label_schema_help_label = QLabel(tt("Bind a label schema first so every specimen uses the same numeric labels for annotation, training, prediction import, and result comparison. Import files should be TaxaMask label schema JSON exported from this panel.", self.lang))
        self.label_schema_help_label.setObjectName("tifLayerHelpText")
        self.label_schema_help_label.setWordWrap(True)
        label_schema_layout.addWidget(self.label_schema_help_label)
        label_schema_select_row = QHBoxLayout()
        label_schema_select_row.setSpacing(6)
        label_schema_select_row.addWidget(self.label_schema_combo, 1)
        label_schema_select_row.addWidget(self.btn_new_label_schema)
        label_schema_layout.addLayout(label_schema_select_row)
        label_schema_form = QFormLayout()
        label_schema_form.setHorizontalSpacing(8)
        label_schema_form.setVerticalSpacing(6)
        self.label_schema_id_label = QLabel("Schema ID")
        self.label_schema_part_name_label = QLabel("User-defined part name")
        label_schema_form.addRow(self.label_schema_id_label, self.label_schema_id_edit)
        label_schema_form.addRow(self.label_schema_part_name_label, self.label_schema_part_name_edit)
        label_schema_layout.addLayout(label_schema_form)
        label_schema_row_buttons = QHBoxLayout()
        label_schema_row_buttons.setSpacing(6)
        label_schema_row_buttons.addWidget(self.btn_add_label_schema_row)
        label_schema_row_buttons.addWidget(self.btn_remove_label_schema_row)
        label_schema_layout.addLayout(label_schema_row_buttons)
        label_schema_layout.addWidget(self.label_schema_table)
        label_schema_save_buttons = QGridLayout()
        label_schema_save_buttons.setHorizontalSpacing(6)
        label_schema_save_buttons.setVerticalSpacing(6)
        label_schema_save_buttons.addWidget(self.btn_save_label_schema, 0, 0)
        label_schema_save_buttons.addWidget(self.btn_bind_label_schema_to_part, 0, 1)
        label_schema_save_buttons.addWidget(self.btn_import_label_schema, 1, 0)
        label_schema_save_buttons.addWidget(self.btn_export_label_schema, 1, 1)
        label_schema_save_buttons.setColumnStretch(0, 1)
        label_schema_save_buttons.setColumnStretch(1, 1)
        label_schema_layout.addLayout(label_schema_save_buttons)
        self.annotation_task_layout.addWidget(self.label_schema_section)
        self.annotation_task_layout.addWidget(self.material_section)
        self.annotation_task_layout.addWidget(self.annotation_section)

        training_section, training_layout = self._make_section("Model training", "tifTrainingSection")
        training_layout.addWidget(self.btn_export_training)
        backend_button_row = QHBoxLayout()
        backend_button_row.addWidget(self.btn_prepare_dataset)
        backend_button_row.addWidget(self.btn_train_backend)
        training_layout.addLayout(backend_button_row)
        training_layout.addWidget(self.backend_run_title_label)
        training_layout.addWidget(self.backend_run_status_label)
        training_layout.addWidget(self.backend_elapsed_label)
        training_layout.addWidget(self.backend_progress_bar)
        backend_run_button_row = QHBoxLayout()
        backend_run_button_row.setSpacing(6)
        backend_run_button_row.addWidget(self.btn_stop_backend)
        backend_run_button_row.addWidget(self.btn_open_backend_run)
        backend_run_button_row.addWidget(self.btn_open_backend_result)
        training_layout.addLayout(backend_run_button_row)
        training_layout.addWidget(self.backend_log_tail)
        part_user_tags_section, part_user_tags_layout = self._make_section("Part group tags", "tifPartUserTagsSection")
        self.part_user_tag_help_label = QLabel(tt("Group tags only organize part volumes for prediction rounds or review batches. They are not annotation classes, label schemas, or training labels.", self.lang))
        self.part_user_tag_help_label.setObjectName("tifLayerHelpText")
        self.part_user_tag_help_label.setWordWrap(True)
        part_user_tags_layout.addWidget(self.part_user_tag_help_label)
        part_tag_form = QFormLayout()
        part_tag_form.setHorizontalSpacing(8)
        part_tag_form.setVerticalSpacing(6)
        self.part_user_tag_id_label = QLabel("Group tag ID")
        self.part_user_tag_label_label = QLabel("Group tag label")
        self.part_user_tag_color_label = QLabel("Color")
        part_tag_form.addRow(self.part_user_tag_id_label, self.part_user_tag_id_edit)
        part_tag_form.addRow(self.part_user_tag_label_label, self.part_user_tag_label_edit)
        part_tag_color_row = QHBoxLayout()
        part_tag_color_row.addWidget(self.part_user_tag_color_swatch)
        part_tag_color_row.addWidget(self.btn_choose_part_user_tag_color, 1)
        part_tag_color_row.addWidget(self.part_user_tag_color_edit)
        part_tag_form.addRow(self.part_user_tag_color_label, part_tag_color_row)
        part_user_tags_layout.addLayout(part_tag_form)
        part_tag_edit_buttons = QGridLayout()
        part_tag_edit_buttons.setHorizontalSpacing(6)
        part_tag_edit_buttons.setVerticalSpacing(6)
        part_tag_edit_buttons.addWidget(self.btn_new_part_user_tag, 0, 0)
        part_tag_edit_buttons.addWidget(self.btn_save_part_user_tag, 0, 1)
        part_tag_edit_buttons.addWidget(self.btn_delete_part_user_tag, 1, 0)
        part_tag_edit_buttons.addWidget(self.btn_apply_part_user_tags, 1, 1)
        part_tag_edit_buttons.setColumnStretch(0, 1)
        part_tag_edit_buttons.setColumnStretch(1, 1)
        part_user_tags_layout.addLayout(part_tag_edit_buttons)
        part_tag_order_buttons = QHBoxLayout()
        part_tag_order_buttons.setSpacing(6)
        part_tag_order_buttons.addWidget(self.btn_move_part_user_tag_up)
        part_tag_order_buttons.addWidget(self.btn_move_part_user_tag_down)
        part_user_tags_layout.addLayout(part_tag_order_buttons)
        part_user_tags_layout.addWidget(self.part_user_tag_table)
        training_layout.addWidget(part_user_tags_section)
        model_library_section, model_library_layout = self._make_section("Trained models", "tifModelLibrarySection")
        self.model_library_label = QLabel("Trained model")
        model_library_layout.addWidget(self.model_library_label)
        model_library_layout.addWidget(self.model_library_combo)
        model_library_layout.addWidget(self.model_library_summary_label)
        self.model_library_notes_label = QLabel("Notes")
        model_library_layout.addWidget(self.model_library_notes_label)
        model_library_layout.addWidget(self.model_library_notes_edit)
        model_library_buttons = QGridLayout()
        model_library_buttons.setHorizontalSpacing(6)
        model_library_buttons.setVerticalSpacing(6)
        model_library_buttons.addWidget(self.btn_use_selected_tif_model, 0, 0)
        model_library_buttons.addWidget(self.btn_save_tif_model_notes, 0, 1)
        model_library_buttons.addWidget(self.btn_delete_tif_model_record, 1, 0, 1, 2)
        model_library_buttons.setColumnStretch(0, 1)
        model_library_buttons.setColumnStretch(1, 1)
        model_library_layout.addLayout(model_library_buttons)
        training_layout.addWidget(model_library_section)
        predict_section, predict_layout = self._make_section("Batch prediction targets", "tifPredictTargetsSection")
        manifest_row = QHBoxLayout()
        manifest_row.setSpacing(6)
        manifest_row.addWidget(self.backend_manifest_edit, 1)
        manifest_row.addWidget(self.btn_browse_model_manifest)
        self.predict_manifest_label = QLabel("Model manifest")
        predict_layout.addWidget(self.predict_manifest_label)
        predict_layout.addLayout(manifest_row)
        filter_row = QHBoxLayout()
        filter_row.setSpacing(6)
        self.predict_filter_label = QLabel("Predict group")
        filter_row.addWidget(self.predict_filter_label)
        filter_row.addWidget(self.predict_filter_combo, 1)
        filter_row.addWidget(self.btn_refresh_predict_targets)
        predict_layout.addLayout(filter_row)
        predict_layout.addWidget(self.predict_targets_table)
        predict_button_row = QHBoxLayout()
        predict_button_row.setSpacing(6)
        predict_button_row.addWidget(self.btn_select_current_predict_target)
        predict_button_row.addWidget(self.btn_select_ready_predict_targets)
        predict_button_row.addWidget(self.btn_clear_predict_targets)
        predict_layout.addLayout(predict_button_row)
        predict_layout.addWidget(self.predict_targets_summary_label)
        predict_layout.addWidget(self.btn_import_prediction)
        predict_layout.addWidget(self.btn_accept_selected_ai_results)
        training_layout.addWidget(predict_section)
        training_layout.addWidget(self.btn_import_external_prediction_tif)
        self.training_task_layout.addWidget(training_section)

        training_result_section, training_result_layout = self._make_section("Training result", "tifTrainingResultSection")
        training_result_layout.addWidget(self.training_result_summary_label)
        training_result_button_grid = QGridLayout()
        training_result_button_grid.setHorizontalSpacing(6)
        training_result_button_grid.setVerticalSpacing(6)
        training_result_button_grid.addWidget(self.btn_show_training_result_summary, 0, 0)
        training_result_button_grid.addWidget(self.btn_open_training_model_output, 0, 1)
        training_result_button_grid.addWidget(self.btn_open_training_model_manifest, 1, 0)
        training_result_button_grid.addWidget(self.btn_batch_predict_entry, 1, 1)
        training_result_button_grid.setColumnStretch(0, 1)
        training_result_button_grid.setColumnStretch(1, 1)
        training_result_layout.addLayout(training_result_button_grid)
        self.training_task_layout.addWidget(training_result_section)

        backend_section, backend_layout = self._make_section("Model configuration", "tifBackendSection")
        backend_form = QFormLayout()
        backend_form.setHorizontalSpacing(8)
        backend_form.setVerticalSpacing(6)
        self.backend_id_label = QLabel("Backend ID")
        self.backend_display_label = QLabel("Display name")
        self.backend_python_label = QLabel("Python")
        self.backend_formats_label = QLabel("Export formats")
        self.backend_prepare_label = QLabel("Prepare command")
        self.backend_train_label = QLabel("Train command")
        self.backend_predict_label = QLabel("Predict command")
        self.backend_manifest_label = QLabel("Model manifest")
        backend_form.addRow(self.backend_id_label, self.backend_id_edit)
        backend_form.addRow(self.backend_display_label, self.backend_display_edit)
        backend_form.addRow(self.backend_python_label, self.backend_python_edit)
        backend_form.addRow(self.backend_formats_label, self.backend_formats_edit)
        backend_form.addRow(self.backend_prepare_label, self.backend_prepare_edit)
        backend_form.addRow(self.backend_train_label, self.backend_train_edit)
        backend_form.addRow(self.backend_predict_label, self.backend_predict_edit)
        self.backend_manifest_label.setVisible(False)
        backend_layout.addLayout(backend_form)
        backend_button_row = QHBoxLayout()
        backend_button_row.setSpacing(6)
        backend_button_row.addWidget(self.btn_use_nnunet_backend_preset)
        backend_button_row.addWidget(self.btn_save_backend)
        backend_button_row.addStretch(1)
        backend_layout.addLayout(backend_button_row)
        self.training_task_layout.addWidget(backend_section)

        log_section, log_layout = self._make_section("Workbench log", "tifLogSection")
        log_layout.addWidget(self.log_console)
        self.training_task_layout.addWidget(log_section)

        result_section, result_layout = self._make_section("Result comparison", "tifResultComparisonSection")
        result_source_row = QHBoxLayout()
        self.result_source_label = QLabel("Review source")
        result_source_row.addWidget(self.result_source_label)
        result_source_row.addWidget(self.result_source_manual_radio)
        result_source_row.addWidget(self.result_source_editable_radio)
        result_source_row.addStretch(1)
        result_layout.addLayout(result_source_row)
        result_region_row = QHBoxLayout()
        self.result_region_label = QLabel("Region label")
        result_region_row.addWidget(self.result_region_label)
        result_region_row.addWidget(self.result_region_combo, 1)
        result_layout.addLayout(result_region_row)
        result_button_grid = QGridLayout()
        result_button_grid.setHorizontalSpacing(8)
        result_button_grid.setVerticalSpacing(8)
        result_button_grid.addWidget(self.btn_refresh_result_comparison, 0, 0)
        result_button_grid.addWidget(self.btn_open_result_comparison_target, 0, 1)
        result_button_grid.addWidget(self.btn_show_result_region_in_3d, 1, 0)
        result_button_grid.addWidget(self.btn_export_current_rendering, 1, 1)
        result_button_grid.setColumnStretch(0, 1)
        result_button_grid.setColumnStretch(1, 1)
        result_layout.addLayout(result_button_grid)
        result_layout.addWidget(self.result_compare_summary_label)
        result_layout.addWidget(self.result_compare_table)
        self.result_compare_layout.addWidget(result_section)
        self.part_task_layout.addStretch(1)
        self.display_task_layout.addStretch(1)
        self.annotation_task_layout.addStretch(1)
        self.training_task_layout.addStretch(1)
        self.result_compare_layout.addStretch(1)
        splitter.addWidget(right)

        self._make_right_sidebar_responsive(right)
        splitter.setSizes([230, 900, 420])
